/* ================================================================
   RecentReportsSection.tsx — Report History & Archive Table
   Phase 10.1: Displays historical generated and demonstration
   reports with instant download and viewer triggers.
   ================================================================ */

import React, { useState, useEffect } from 'react';
import { reportService } from '../../services/reportService';
import type { RecentReportItem } from '../../types/report';
import ReportViewerModal from './ReportViewerModal';

export default function RecentReportsSection() {
  const [reports, setReports] = useState<RecentReportItem[]>([]);
  const [activeReport, setActiveReport] = useState<any>(null);

  useEffect(() => {
    setReports(reportService.getRecentReports());
  }, []);

  const handleDownload = (item: RecentReportItem) => {
    if (item.reportData && item.reportData.title) {
      reportService.downloadReportHtml(item.reportData);
    } else {
      // Re-create demonstration dummy document for export
      const dummyReport = {
        id: item.id,
        title: item.title,
        type: item.type,
        machineId: 'ALL' as const,
        machineName: item.machineName,
        generatedBy: {
          id: 'USR-DEMO',
          name: item.generatedBy,
          role: item.generatedByRole,
        },
        generatedAt: item.date,
        dateRange: 'LAST 24 HOURS',
        executiveSummary: {
          totalMachines: 8,
          healthyCount: 5,
          warningCount: 2,
          criticalCount: 1,
          averageFleetHealth: 81.5,
          activeAlerts: 3,
          machinesRequiringMaintenance: 3,
        },
        config: {} as any,
      };
      reportService.downloadReportHtml(dummyReport as any);
    }
  };

  const handleView = (item: RecentReportItem) => {
    if (item.reportData && item.reportData.title) {
      setActiveReport(item.reportData);
    } else {
      // Generate demonstration report structure
      const demoDoc = {
        id: item.id,
        title: item.title,
        type: item.type,
        machineId: 'ALL' as const,
        machineName: item.machineName,
        generatedBy: {
          id: 'USR-DEMO',
          name: item.generatedBy,
          role: item.generatedByRole,
        },
        generatedAt: item.date,
        dateRange: 'LAST 24 HOURS',
        executiveSummary: {
          totalMachines: 8,
          healthyCount: 5,
          warningCount: 2,
          criticalCount: 1,
          averageFleetHealth: 81.5,
          activeAlerts: 3,
          machinesRequiringMaintenance: 3,
        },
        machineHealth: [
          { id: 1, name: 'Motor IM-001', type: '3-Phase Induction Motor', health: 100, state: 'NORMAL', risk: 'LOW', fault: 'None (Healthy)' },
          { id: 20, name: 'Motor IM-002', type: '3-Phase Induction Motor', health: 76, state: 'WARNING', risk: 'MEDIUM', fault: 'Bearing Degradation' },
          { id: 21, name: 'Motor IM-003', type: '3-Phase Induction Motor', health: 42, state: 'CRITICAL', risk: 'HIGH', fault: 'Stator Short / Overheating' },
        ],
        recommendations: [
          { machineId: 21, machineName: 'Motor IM-003', severity: 'CRITICAL' as const, recommendation: 'Immediate shutdown and stator inspection required.', justification: 'Vibration 7.2 mm/s and temperature 98°C exceed safe limits.' },
          { machineId: 20, machineName: 'Motor IM-002', severity: 'WARNING' as const, recommendation: 'Re-lubricate drive-end bearing and align shaft.', justification: 'Vibration elevated at 4.9 mm/s.' },
        ],
        config: {} as any,
      };
      setActiveReport(demoDoc);
    }
  };

  return (
    <div className="section" id="section-recent-reports">
      <div className="section-header">
        <div className="section-header__left">
          <span className="section-header__icon">📄</span>
          <span className="section-header__title">Recent Reports</span>
          <span className="demo-tag">Demonstration History</span>
        </div>
      </div>

      <div className="table-responsive">
        <table className="data-table">
          <thead>
            <tr>
              <th>Report Title</th>
              <th>Scope</th>
              <th>Generated By</th>
              <th>Date</th>
              <th>Status</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            {reports.map((item) => (
              <tr key={item.id}>
                <td>
                  <div style={{ fontWeight: 700, color: 'var(--text-primary)' }}>{item.title}</div>
                  <div style={{ fontSize: '0.68rem', color: 'var(--text-muted)', fontFamily: 'var(--font-mono)' }}>
                    ID: {item.id}
                  </div>
                </td>
                <td>
                  <span style={{ fontSize: '0.76rem', color: 'var(--text-secondary)' }}>
                    {item.machineName}
                  </span>
                </td>
                <td>
                  <div style={{ fontSize: '0.78rem', fontWeight: 600, color: 'var(--text-primary)' }}>
                    {item.generatedBy}
                  </div>
                  <div style={{ fontSize: '0.67rem', color: 'var(--text-muted)' }}>
                    {item.generatedByRole}
                  </div>
                </td>
                <td style={{ fontSize: '0.74rem', color: 'var(--text-muted)', fontFamily: 'var(--font-mono)' }}>
                  {item.date}
                </td>
                <td>
                  <span
                    className="status-badge"
                    style={{
                      background: 'rgba(34, 197, 94, 0.1)',
                      color: 'var(--color-healthy)',
                      fontSize: '0.68rem',
                    }}
                  >
                    ● {item.status}
                  </span>
                </td>
                <td>
                  <div style={{ display: 'flex', gap: 8 }}>
                    <button
                      className="btn btn--secondary"
                      onClick={() => handleView(item)}
                      style={{ padding: '4px 8px', fontSize: '0.72rem' }}
                    >
                      View
                    </button>
                    <button
                      className="btn btn--secondary"
                      onClick={() => handleDownload(item)}
                      style={{ padding: '4px 8px', fontSize: '0.72rem' }}
                    >
                      Download
                    </button>
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {activeReport && (
        <ReportViewerModal
          report={activeReport}
          onClose={() => setActiveReport(null)}
        />
      )}
    </div>
  );
}
