/* ================================================================
   ReportViewerModal.tsx — Structured Industrial Report Document Viewer
   Phase 10.1: Interactive in-browser report presentation with
   executive styling, role stamp, print-to-PDF, and export.
   ================================================================ */

import React from 'react';
import type { GeneratedReport } from '../../types/report';
import { reportService } from '../../services/reportService';

interface Props {
  report: GeneratedReport;
  onClose: () => void;
}

export default function ReportViewerModal({ report, onClose }: Props) {
  const exec = report.executiveSummary;
  const machines = report.machineHealth || [];
  const sensors = report.sensorSummary || [];
  const predictive = report.predictive || [];
  const recommendations = report.recommendations || [];

  const handlePrint = () => {
    const printable = reportService.renderPrintableHtml(report);
    const printWindow = window.open('', '_blank');
    if (printWindow) {
      printWindow.document.write(printable);
      printWindow.document.close();
      printWindow.focus();
      setTimeout(() => {
        printWindow.print();
      }, 300);
    }
  };

  const handleDownload = () => {
    reportService.downloadReportHtml(report);
  };

  return (
    <div className="modal-backdrop" style={{ zIndex: 1100 }}>
      <div
        className="modal-content"
        style={{
          width: '900px',
          maxWidth: '96vw',
          maxHeight: '92vh',
          display: 'flex',
          flexDirection: 'column',
          padding: 0,
          overflow: 'hidden',
          background: 'var(--bg-primary)',
          borderRadius: 'var(--radius-lg)',
          boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.7)',
        }}
      >
        {/* Header Action Bar */}
        <div
          style={{
            padding: '16px 24px',
            borderBottom: '1px solid var(--border-color)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            background: 'var(--bg-secondary)',
          }}
        >
          <div>
            <span style={{ fontSize: '0.68rem', color: 'var(--color-primary)', fontWeight: 800, letterSpacing: '0.08em' }}>
              OFFICIAL SYSTEM REPORT • {report.id}
            </span>
            <div style={{ fontSize: '1.05rem', fontWeight: 800, color: 'var(--text-primary)' }}>
              {report.title}
            </div>
          </div>

          <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
            <button className="btn btn--secondary" onClick={handlePrint} style={{ fontSize: '0.8rem', padding: '6px 12px' }}>
              🖨 Print / PDF
            </button>
            <button className="btn btn--primary" onClick={handleDownload} style={{ fontSize: '0.8rem', padding: '6px 12px' }}>
              ↓ Download HTML
            </button>
            <button
              onClick={onClose}
              style={{
                background: 'transparent',
                border: 'none',
                color: 'var(--text-muted)',
                fontSize: '1.3rem',
                cursor: 'pointer',
                padding: '4px 8px',
              }}
            >
              ✕
            </button>
          </div>
        </div>

        {/* Scrollable Document Container */}
        <div style={{ flex: 1, overflowY: 'auto', padding: '28px 36px' }}>
          {/* Document Header Stamp */}
          <div
            style={{
              borderBottom: '2px solid var(--border-color)',
              paddingBottom: '20px',
              marginBottom: '24px',
              display: 'flex',
              justifyContent: 'space-between',
              alignItems: 'flex-start',
            }}
          >
            <div>
              <div style={{ fontSize: '1.1rem', fontWeight: 900, color: 'var(--color-primary)', letterSpacing: '0.05em' }}>
                MACHINA-X <span>PREDICTIVE MAINTENANCE SYSTEM</span>
              </div>
              <div style={{ fontSize: '1.25rem', fontWeight: 800, margin: '8px 0', color: 'var(--text-primary)' }}>
                {report.title}
              </div>
              <div
                style={{
                  display: 'inline-flex',
                  alignItems: 'center',
                  gap: 8,
                  background: 'rgba(77, 157, 224, 0.08)',
                  border: '1px solid rgba(77, 157, 224, 0.25)',
                  padding: '4px 12px',
                  borderRadius: 4,
                  fontSize: '0.78rem',
                  color: 'var(--color-primary)',
                }}
              >
                <span>👤</span>
                <span>
                  Generated by: <strong>{report.generatedBy.name}</strong> ({report.generatedBy.role}) [DEMONSTRATION]
                </span>
              </div>
            </div>

            <div style={{ textAlign: 'right', fontSize: '0.76rem', color: 'var(--text-muted)', fontFamily: 'var(--font-mono)' }}>
              <div><strong>Document ID:</strong> {report.id}</div>
              <div><strong>Generated:</strong> {report.generatedAt}</div>
              <div><strong>Target:</strong> {report.machineName}</div>
              <div><strong>Time Range:</strong> {report.dateRange}</div>
            </div>
          </div>

          {/* 1. Executive Summary */}
          {exec && (
            <div style={{ marginBottom: '28px' }}>
              <div style={{ fontSize: '0.85rem', fontWeight: 800, color: 'var(--text-primary)', textTransform: 'uppercase', letterSpacing: '0.06em', marginBottom: '12px' }}>
                1. Executive Summary
              </div>
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 12, marginBottom: '14px' }}>
                <div style={{ background: 'var(--bg-secondary)', border: '1px solid var(--border-color)', borderRadius: 'var(--radius-md)', padding: '14px', textAlign: 'center' }}>
                  <div style={{ fontSize: '1.6rem', fontWeight: 800, color: 'var(--text-primary)' }}>{exec.totalMachines}</div>
                  <div style={{ fontSize: '0.68rem', color: 'var(--text-muted)', textTransform: 'uppercase', marginTop: 4 }}>Total Machines</div>
                </div>
                <div style={{ background: 'var(--bg-secondary)', border: '1px solid var(--border-color)', borderRadius: 'var(--radius-md)', padding: '14px', textAlign: 'center' }}>
                  <div style={{ fontSize: '1.6rem', fontWeight: 800, color: 'var(--color-healthy)' }}>{exec.healthyCount}</div>
                  <div style={{ fontSize: '0.68rem', color: 'var(--text-muted)', textTransform: 'uppercase', marginTop: 4 }}>Healthy</div>
                </div>
                <div style={{ background: 'var(--bg-secondary)', border: '1px solid var(--border-color)', borderRadius: 'var(--radius-md)', padding: '14px', textAlign: 'center' }}>
                  <div style={{ fontSize: '1.6rem', fontWeight: 800, color: 'var(--color-warning)' }}>{exec.warningCount}</div>
                  <div style={{ fontSize: '0.68rem', color: 'var(--text-muted)', textTransform: 'uppercase', marginTop: 4 }}>Warning</div>
                </div>
                <div style={{ background: 'var(--bg-secondary)', border: '1px solid var(--border-color)', borderRadius: 'var(--radius-md)', padding: '14px', textAlign: 'center' }}>
                  <div style={{ fontSize: '1.6rem', fontWeight: 800, color: 'var(--color-critical)' }}>{exec.criticalCount}</div>
                  <div style={{ fontSize: '0.68rem', color: 'var(--text-muted)', textTransform: 'uppercase', marginTop: 4 }}>Critical</div>
                </div>
              </div>
              <div style={{ fontSize: '0.8rem', color: 'var(--text-secondary)', background: 'var(--bg-card)', padding: '10px 14px', borderRadius: 6, border: '1px solid var(--border-color)' }}>
                Average Fleet Health: <strong style={{ color: 'var(--text-primary)' }}>{exec.averageFleetHealth !== null ? `${exec.averageFleetHealth}%` : 'N/A'}</strong> •
                Active Sensor Alerts: <strong style={{ color: 'var(--text-primary)' }}>{exec.activeAlerts}</strong> •
                Machines Requiring Maintenance: <strong style={{ color: 'var(--text-primary)' }}>{exec.machinesRequiringMaintenance}</strong>
              </div>
            </div>
          )}

          {/* 2. Machine Health Table */}
          {machines.length > 0 && (
            <div style={{ marginBottom: '28px' }}>
              <div style={{ fontSize: '0.85rem', fontWeight: 800, color: 'var(--text-primary)', textTransform: 'uppercase', letterSpacing: '0.06em', marginBottom: '12px' }}>
                2. Machine Health & Operating Matrix
              </div>
              <div className="table-responsive">
                <table className="data-table">
                  <thead>
                    <tr>
                      <th>Machine</th>
                      <th>Type</th>
                      <th>Health</th>
                      <th>State</th>
                      <th>Risk</th>
                      <th>Fault Classification</th>
                    </tr>
                  </thead>
                  <tbody>
                    {machines.map((m) => (
                      <tr key={m.id}>
                        <td><strong>{m.name}</strong></td>
                        <td style={{ fontSize: '0.74rem', color: 'var(--text-muted)' }}>{m.type}</td>
                        <td>
                          <strong style={{ color: m.health >= 80 ? 'var(--color-healthy)' : m.health >= 60 ? 'var(--color-warning)' : 'var(--color-critical)' }}>
                            {m.health}%
                          </strong>
                        </td>
                        <td>
                          <span
                            className="status-badge"
                            style={{
                              background: m.state === 'CRITICAL' ? 'var(--color-critical-bg)' : m.state === 'WARNING' || m.state === 'WATCH' ? 'var(--color-warning-bg)' : 'var(--color-healthy-bg)',
                              color: m.state === 'CRITICAL' ? 'var(--color-critical)' : m.state === 'WARNING' || m.state === 'WATCH' ? 'var(--color-warning)' : 'var(--color-healthy)',
                              fontSize: '0.68rem',
                            }}
                          >
                            ● {m.state}
                          </span>
                        </td>
                        <td>
                          <span style={{ fontSize: '0.74rem', fontWeight: 700, color: m.risk === 'HIGH' ? 'var(--color-critical)' : m.risk === 'MEDIUM' ? 'var(--color-warning)' : 'var(--color-healthy)' }}>
                            {m.risk}
                          </span>
                        </td>
                        <td style={{ fontSize: '0.76rem', color: 'var(--text-secondary)' }}>{m.fault}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          )}

          {/* 3. Sensor Summary */}
          {sensors.length > 0 && (
            <div style={{ marginBottom: '28px' }}>
              <div style={{ fontSize: '0.85rem', fontWeight: 800, color: 'var(--text-primary)', textTransform: 'uppercase', letterSpacing: '0.06em', marginBottom: '12px' }}>
                3. Multi-Sensor Telemetry Summary
              </div>
              <div className="table-responsive">
                <table className="data-table">
                  <thead>
                    <tr>
                      <th>Machine</th>
                      <th>DE Vibration</th>
                      <th>Winding Temp</th>
                      <th>Stator Current</th>
                      <th>Rotor Speed</th>
                      <th>Est. Load</th>
                    </tr>
                  </thead>
                  <tbody>
                    {sensors.map((s, idx) => (
                      <tr key={idx}>
                        <td><strong>{s.machineName}</strong></td>
                        <td style={{ fontFamily: 'var(--font-mono)' }}>{s.vibration}</td>
                        <td style={{ fontFamily: 'var(--font-mono)' }}>{s.temperature}</td>
                        <td style={{ fontFamily: 'var(--font-mono)' }}>{s.current}</td>
                        <td style={{ fontFamily: 'var(--font-mono)' }}>{s.rpm}</td>
                        <td style={{ fontFamily: 'var(--font-mono)' }}>{s.load}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          )}

          {/* 4. Predictive Maintenance & RUL */}
          {predictive.length > 0 && (
            <div style={{ marginBottom: '28px' }}>
              <div style={{ fontSize: '0.85rem', fontWeight: 800, color: 'var(--text-primary)', textTransform: 'uppercase', letterSpacing: '0.06em', marginBottom: '12px' }}>
                4. Predictive Maintenance & Remaining Useful Life (RUL)
              </div>
              <div className="table-responsive">
                <table className="data-table">
                  <thead>
                    <tr>
                      <th>Machine</th>
                      <th>Failure Risk</th>
                      <th>Est. RUL</th>
                      <th>Predicted Fault</th>
                      <th>Recommended Action</th>
                    </tr>
                  </thead>
                  <tbody>
                    {predictive.map((p, idx) => (
                      <tr key={idx}>
                        <td><strong>{p.machineName}</strong></td>
                        <td>
                          <span style={{ fontSize: '0.74rem', fontWeight: 700, color: p.failureRisk === 'HIGH' ? 'var(--color-critical)' : p.failureRisk === 'MEDIUM' ? 'var(--color-warning)' : 'var(--color-healthy)' }}>
                            {p.failureRisk}
                          </span>
                        </td>
                        <td style={{ fontFamily: 'var(--font-mono)', fontWeight: 700 }}>{p.rulDays} days</td>
                        <td style={{ fontSize: '0.74rem', color: 'var(--text-secondary)' }}>{p.predictedFault}</td>
                        <td style={{ fontSize: '0.74rem', color: 'var(--text-muted)' }}>{p.recommendedAction}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          )}

          {/* 5. Condition-Based Maintenance Recommendations */}
          <div style={{ marginBottom: '28px' }}>
            <div style={{ fontSize: '0.85rem', fontWeight: 800, color: 'var(--text-primary)', textTransform: 'uppercase', letterSpacing: '0.06em', marginBottom: '12px' }}>
              5. Condition-Based Maintenance Recommendations
            </div>
            {recommendations.length > 0 ? (
              <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
                {recommendations.map((r, idx) => (
                  <div
                    key={idx}
                    style={{
                      background: r.severity === 'CRITICAL' ? 'rgba(239, 68, 68, 0.08)' : 'rgba(245, 158, 11, 0.08)',
                      borderLeft: `4px solid ${r.severity === 'CRITICAL' ? 'var(--color-critical)' : 'var(--color-warning)'}`,
                      borderTop: `1px solid ${r.severity === 'CRITICAL' ? 'rgba(239, 68, 68, 0.2)' : 'rgba(245, 158, 11, 0.2)'}`,
                      borderRight: `1px solid ${r.severity === 'CRITICAL' ? 'rgba(239, 68, 68, 0.2)' : 'rgba(245, 158, 11, 0.2)'}`,
                      borderBottom: `1px solid ${r.severity === 'CRITICAL' ? 'rgba(239, 68, 68, 0.2)' : 'rgba(245, 158, 11, 0.2)'}`,
                      borderRadius: 'var(--radius-md)',
                      padding: '12px 16px',
                    }}
                  >
                    <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 4 }}>
                      <span style={{ fontWeight: 800, fontSize: '0.82rem', color: 'var(--text-primary)' }}>
                        [{r.severity}] {r.machineName} Directive
                      </span>
                    </div>
                    <div style={{ fontSize: '0.78rem', color: 'var(--text-primary)', lineHeight: 1.5 }}>
                      {r.recommendation}
                    </div>
                    <div style={{ fontSize: '0.7rem', color: 'var(--text-muted)', marginTop: 4, fontStyle: 'italic' }}>
                      Justification: {r.justification}
                    </div>
                  </div>
                ))}
              </div>
            ) : (
              <div
                style={{
                  background: 'rgba(34, 197, 94, 0.08)',
                  border: '1px solid rgba(34, 197, 94, 0.2)',
                  borderRadius: 'var(--radius-md)',
                  padding: '14px 18px',
                  color: 'var(--color-healthy)',
                  fontSize: '0.82rem',
                }}
              >
                ✓ All monitored machines are within normal baseline thresholds. No abnormal condition-based recommendations required at this time.
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
